# Generated by Django 6.0.5 on 2026-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMYJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('site_name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField(default=2005)),
                ('end_year', models.IntegerField(default=2023)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
