# Generated by Django 6.0.5 on 2026-06-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmyjob',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tmyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading_era5', 'Downloading ERA5 Data'), ('downloading_cams', 'Downloading CAMS Data'), ('processing_data', 'Processing Data'), ('generating_tmy', 'Generating TMY'), ('generating_report', 'Generating Report'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
