# Generated by Django 6.0.5 on 2026-06-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmy_app', '0002_tmyjob_status_message_alter_tmyjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('downloading_era5', 'Downloading ERA5 Data'), ('downloading_cams', 'Downloading CAMS Data'), ('processing_data', 'Processing Data'), ('generating_tmy', 'Generating TMY'), ('generating_report', 'Generating Report'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
