# Generated by Django 6.0.5 on 2026-06-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmy_app', '0004_tmyjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmyjob',
            name='job_type',
            field=models.CharField(choices=[('full', 'Download + Generate TMY'), ('download_only', 'Download Data Only')], default='full', max_length=20),
        ),
    ]
