# Generated by Django 6.0.5 on 2026-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmy_app', '0005_tmyjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmyjob',
            name='selected_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
